version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      playwright:
        patterns:
          - 'playwright*'
          - 'puppeteer-extra-plugin-stealth'
      opentelemetry:
        patterns:
          - '@opentelemetry/*'
      types:
        patterns:
          - '@types/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
